apiVersion: v1
kind: Service
metadata:
  name: dotnetcoreapp 
  labels:
    app: dotnetcoreapp 
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 8081
    protocol: TCP
  selector:
    app: dotnetcoreapp